apiVersion: v1
kind: Service
metadata:
  name: {{.app}}
spec:
  selector:
    app: {{.app}}
    tier: {{.tier}}
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.app}}
    tier: {{.tier}}
  name: {{.app}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.app}}
  template:
    metadata:
      labels:
        app: {{.app}}
        tier: {{.tier}}
    spec:
      containers:
      - image: {{.image}}
        # imagePullPolicy: IfNotPresent
        name: {{.app}}
        ports:
        - containerPort: 3000
          protocol: TCP
      terminationGracePeriodSeconds: 30
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
