#import "~/apollo/fragments/searchResultOrganization.gql"

query fetchOrganizationById ($id: ID!) {
  Organization(where: { id: $id }) {
    id
    name
    alternative
    other_names
    identifiers
    classification
    abstract
    description
    founding_date_year
    founding_date_month
    founding_date_day
    dissolution_date_year
    dissolution_date_month
    dissolution_date_day
    image
    contact_details
    links
    address
    source
    tags {
      id
      name
    }
  }
}

query fetchOrganizationCount {
  _allOrganizationsMeta {
    count
  }
}

query searchOrganizations($text: String) {
  name: allOrganizations(search: $text) {
    ...searchResultOrganization
	}
  alternative: allOrganizations (where:{ alternative_contains: $text }) {
    ...searchResultOrganization
  }
}
