query fetchOrganizationRelationById ($id: ID!) {
  OrganizationRelation(where: { id: $id }) {
    id
    organization_id {
      id
      name
    }
    related_organization_id {
      id
      name
    }
    relative
    start_date_year
    start_date_month
    start_date_day
    end_date_year
    end_date_month
    end_date_day
    source
    tags {
      id
      name
    }
  }
}

query fetchOrganizationRelationsCount {
  _allOrganizationRelationsMeta {
    count
  }
}
