query fetchPersonRelationById ($id: ID!) {
  PersonRelation(where: { id: $id }) {
    id
    person_id {
      id
      name
    }
    related_person_id {
      id
      name
    }
    relative
    start_date_year
    start_date_month
    start_date_day
    end_date_year
    end_date_month
    end_date_day
    source
    tags {
      id
      name
    }
  }
}

query fetchPersonRelationsCount {
  _allPersonRelationsMeta {
    count
  }
}

query searchPersonRelations($personName: String!, $relatedPersonName: String!) {
  allPersonRelations(
    where: {
      person_id: {
        name: $personName
      },
      related_person_id: {
        name: $relatedPersonName
      }
    }
  ) {
    id
    relative
    person_id {
      id
      name
    }
    related_person_id {
      id
      name
    }
  }
}
