query fetchPersonOrganizationById ($id: ID!) {
  PersonOrganization(where: { id: $id }) {
    id
    person_id {
      id
      name
    }
    organization_id {
      id
      name
    }
    role
    start_date_year
    start_date_month
    start_date_day
    end_date_year
    end_date_month
    end_date_day
    source
    tags {
      id
      name
    }
  }
}

query fetchPersonOrganizationsCount {
  _allPersonOrganizationsMeta {
    count
  }
}

query searchPersonOrganizations($personName: String!, $organizationName: String!) {
  allPersonOrganizations(
    where: {
      person_id: {
        name: $personName
      },
      organization_id:{
        name: $organizationName
      }
    }
  ) {
    id
    role
    person_id {
      id
      name
    }
    organization_id {
      id
      name
    }
  }
}
