#import "~/apollo/fragments/searchResultPerson.gql"

query fetchPersonById ($id: ID!) {
  Person(where: { id: $id }) {
    id
    name
    alternative
    other_names
    email
    gender
    birth_date_year
    birth_date_month
    birth_date_day
    death_date_year
    death_date_month
    death_date_day
    image
    summary
    biography
    national_identity
    contact_details
    links
    source
    tags {
      id
      name
    }
  }
}

query fetchPersonCount {
  _allPersonsMeta {
    count
  }
}

query searchPersons($text: String) {
  name: allPersons(search: $text) {
    ...searchResultPerson
	}
  alternative: allPersons (where:{ alternative_contains: $text }) {
    ...searchResultPerson
  }
}
