export const organizationFields = {
  name: {
    label: "組織名稱",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  alternative: {
    label: "組織別名",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  other_names: {
    label: "組織舊名",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  identifiers: {
    label: "統一編號",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  classification: {
    label: "組織類型",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  area: {
    label: "組織地區",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  abstract: {
    label: "一句話描述該組織",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  description: {
    label: "組織詳細介紹",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  founding_date: {
    label: "創立時間",
    info: "",
    value: "",
    inputStatus: { type: "date" },
  },
  dissolution_date: {
    label: "解散時間",
    info: "",
    value: "",
    inputStatus: { type: "date" },
  },
  image: {
    label: "圖像",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  contact_details: {
    label: "聯絡方式",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  links: {
    label: "網站",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  address: {
    label: "組織稅籍登記地址",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  source: {
    label: "來源",
    info: "",
    value: "",
    inputStatus: { type: "text" },
  },
  //area: { label: "地區", type: Relationship, many: false, ref: 'Area' },
  //memberships: { label: "成員", type: Relationship, many: true, ref: 'Membership' },
  //posts: { label: "posts", type: Relationship, many: true, ref: 'Post' },
  //motions: { label: "發起活動", type: Relationship, many: true, ref: 'Motion' },
  //vote_events: { label: "選舉/投票", type: Relationship, many: true, ref: 'Vote_event' },
  //votes: { label: "votes", type: Relationship, many: true, ref: 'Vote' },
  //identifiers: { label: "identifiers", type: Relationship, many: false, ref: 'User',  isRequired: true},
};
